### ISSUE TITLE
Clarification about the Jacobean Matrix

### ISSUE THREAD

**Issue by Tabibrh** [sibirrer/fastell4py#2]
So I am a student and i have gone through the paper and since i am better at python hence using this which was a great help. I think it's not an issue but maybe because i am a novice at this , fastellmag basically should pull out the Jacobean as in the manual , but while going through the commands i have a doubt , f_xx , f_yy, fxy is this the different component of the Jacobean if not how do I pull out the Jacobean i mean with what command.

**Comment by sibirrer** [comment]
Hi @Tabibrh, thanks for reaching out. These are the different components of the Jacobian. You can also have a look at the lenstronomy functions that call fastell2py here: https://github.com/lenstronomy/lenstronomy/blob/main/lenstronomy/LensModel/Profiles/spemd.py

**Comment by Tabibrh** [comment]
Okay last question , what about the f_yx  ?

**Comment by sibirrer** [comment]
this is the derivative df^2/dxdy with f being the lensing potential. Basically the off-diagonal of the Jacobian.

**Comment by Tabibrh** [comment]
Okayyy Thanks
